config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  # usersコントローラー
  get  '/signup', to: 'users#new'
  get '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update-basic-info', to: 'users#update_basic_info'
  get  '/attendance_log', to: 'users#attendance_log'
  get  '/working_users', to: 'users#working_users'
  get  '/base_edit', to: 'users#base_edit'
  
  #拠点テスト
  get  '/test00', to: 'users#test00'
  #get  '/test00/:id', to: 'users#test00', as: :test
  #patch 'update-test00', to: 'users#update_test00'
  
  #テスト発展
  get  '/test01/:id', to: 'users#test01', as: :test01
  patch 'update-test01', to: 'users#update_test01'
  
  #get  '/test00/:id', to: 'users#base_edit', as: :test00
  #patch 'update-test00', to: 'users#update_test01'
  
  
  # sessionsコントローラー
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # users>attendancesコントローラー
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  
  resources :users do
    resources :attendances, only: :create
    
    #拠点編集ページルーティング
    collection do
      #get  'base_edit'
      #post 'base_add'
      
      #get 'base_update'
      
      delete 'base_delete'
      #get 'base_edit_modal'
    end
    
    member do
      #ユーザー覧編集機能のため追加 membr do でルーティングする方法が不明（ない場合noMETHODエラー）
      patch  'update_by_admin'  #, as: :update_by_admin　ルートに名前をつける必要なし
    end
    
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy # １対多の関連性を示すことが出来ます。
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :department, length: { in: 3..50 }, allow_blank: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  #ユーザー覧を管理者のみアクセス可能にするため:indexを追加
  before_action :admin_user,     only: [:destroy, :edit_basic_info, :update_basic_info, :index]
  
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @first_day = first_day(params[:first_day])
    @last_day = @first_day.end_of_month
    (@first_day..@last_day).each do |day|
      unless @user.attendances.any? {|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    @dates = user_attendances_month_date
    @worked_sum = @dates.where.not(started_at: nil).count
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザーの新規作成に成功しました。"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    #@user = User.find(params[:id]) /def correct_userで実行するため必要なし
  end
  
  def update
    #@user = User.find(params[:id]) /def correct_userで実行するため必要なし
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  #勤怠aユーザー覧表示のため追加
  def update_by_admin
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "アカウントを更新しました。"
      redirect_to users_path
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
    @user = User.find(params[:id])
  end
  
  def update_basic_info
    @user = User.find(params[:id])
    if @user.update_attributes(basic_info_params)
      flash[:success] = "基本情報を更新しました。"
      redirect_to @user   
    else
      render 'edit_basic_info'
    end
  end
  
  def attendance_log
  end
  
  def working_users
    #暫定的に変数設置ページネイション確認のため
    #@users = User.paginate(page: params[:page])
    @users = User.where(working: '出社中').paginate(page: params[:page])
  end
  
  def base_edit
    @bases = Base.all
    @base = Base.new
    @user = User.new
    
  end
  
  # def base_update
  #   @base = Base.find(params[:id])
  #     if @base.update(base_params)
  #       flash[:success] = "拠点情報を更新しました。"
  #       redirect_to base_edit_users_path
  #     else
  #       render 'base_edit'
  #     end
  # end
  
  def base_delete
    @base = Base.find(params[:id])
      if @base.destroy
        flash[:danger] = "拠点情報を削除しました。"
        redirect_to base_edit_users_path
      else
        render 'base_edit'
      end
  end
  
  
  #テストページ
  def test00
    @user = User.find(params[:id])
    #@bases = Base.all
  end
  
  def update_test00
    @user = User.find(params[:id])
    if @user.update_attributes(basic_info_params)
      flash[:success] = "基本情報を更新しました。"
      redirect_to @user   
    else
      render 'base_edit'
    end
  end
  
    #テストページ1
  def test01
    #@user = User.find(params[:id])
    @base = Base.find(params[:id])
    #binding.pry
  end
  
  def update_test01
    #binding.pry
    @base = Base.find(params[:id])
    if @base.update_attributes(base_params)
      flash[:success] = "拠点を更新しました。"
      redirect_to '/base_edit'
    else
      render 'base_edit'
    end
  end
  
  
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :department, :password,:password_confirmation,
                                                                                      :work_time,
                                                                                      :work_start,
                                                                                      :work_end,
                                                                                      :work_number,
                                                                                      :worker_id,)
    end
    
    # beforeアクション

    # ログイン済みユーザーか確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end
    
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
    def basic_info_params
      params.require(:user).permit(:basic_time, :work_time)
    end
    
    def base_params
      params.require(:base).permit(:base_number, :base_name)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
    # 基本時間などの値を、指定の書式にフォーマットして返す
  def format_basic_time(datetime)
    format("%.2f", ((datetime.hour * 60) + datetime.min)/60.0)
  end
end

app/views/users/_base_edit_modal.html.erb
<% provide(:title, "基本情報編集") %>

<h1>基本情報の編集</h1>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :名前 %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :メールアドレス %>
  <%= f.email_field :email, class: 'form-control' %>
  
  <%= f.label :所属 %>
  <%= f.text_field :department, class: 'form-control' %>

  <%= f.label :パスワード %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :パスワード確認 %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_test00.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :department %>
  <%= f.text_field :department, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= user.name %><br>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "削除", user, class: "btn btn-primary", method: :delete,
                                  data: { confirm: "削除してもいいですか？" } %>
  
        <div class="panel-group" id="accordion-<%= user.id %>">
	        <div class="panel panel-default">
		        <div class="panel-heading">
			        <h3 class="panel-title">
				        <a class="btn btn-primary btn-lg btn-a" data-toggle="collapse" data-parent="#accordion-<%= user.id %>" href="#accordionCollapse1-<%= user.id %>" >
					        編集
				        </a>
			        </h3>
		        </div>
		    <div id="accordionCollapse1-<%= user.id%>" class="panel-collapse collapse">
    			<div class="panel-body">
    			  
    			  <!--なぜ_user_pathか不明-->
    				<%= form_for user, url: update_by_admin_user_path(user) do |f| %>
    				  <%= f.label :名前 %>
            <%= f.text_field :name, class: 'form-control' %>
      
            <%= f.label :メールアドレス %>
            <%= f.email_field :email, class: 'form-control' %>
            
            <%= f.label :所属 %>
            <%= f.text_field :department, class: 'form-control' %>
            
            <%= f.label :社員番号 %>
            <%= f.text_field :work_number, class: 'form-control' %>
            
            <%= f.label :カードID%>
            <%= f.text_field :worker_id, class: 'form-control' %>
      
            <%= f.label :パスワード %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :基本勤務時間 %>
            <%= f.time_field :basic_time,{class: 'form-control'} %>
            
            <%= f.label :指定勤務開始時間 %>
            <%= f.time_field :work_start,{class: 'form-control'} %>
            
            <%= f.label :指定勤務終了時間 %>
            <%= f.time_field :work_end,{class: 'form-control'} %>
            
            <%= f.submit "編集する", class: "btn btn-primary test" %>
            <a class="btn btn-primary" data-toggle="collapse" data-parent="#accordion-<%= user.id %>" href="#accordionCollapse1-<%= user.id %>" >
					     閉じる
				    </a>
    				<% end %>
    			</div>
		</div>
	</div>
	
</div>
    
  <% end %>
</li>

app/views/users/_working_index.html.erb
<table class="table table-bordered working-table table-striped">
    <thead>
        <tr>
            <th>社員番号</th>
            <th>名前</th>
        </tr>
    </thead>
    <tbody>
        <% users.each do |user| %>
        <tr>
            <td><%= user.work_number %></td>
            <td><%= user.name %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/users/attendance_log.html.erb
<% provide(:title, '勤怠修正ログ') %>

<h1>勤怠修正ログ</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= "勤怠修正ログ" %>
  </div>
</div>

app/views/users/base_edit.html.erb
<% provide(:title, '拠点一覧') %>

<html lang="ja">
  <head>
      <meta charset="utf-8">
      <title>テスト</title>
      <!--CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
      <!--JS -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  </head>

  <h1>拠点一覧</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      
      <table class="table table-bordered working-table table-striped">
          <thead>
              <tr>
                  <th></th>
                  <th></th>
                  <th>拠点番号</th>
                  <th>拠点名</th>
                  <th>勤怠種類</th>
              </tr>
          </thead>
          <tbody>
              <% @bases.each do |base| %>
              <tr>
                  <td><%= link_to "基本情報編集てすと", test01_path(id: base.id) %></td>
                  
                  
                  <td><%= link_to "削除", base_delete_users_path(id: base.id), class: "btn btn-primary", method: :delete,
                      data: { confirm: "本当に削除してもいいですか？" } %></td>
                  <td><%= base.base_number %></td>
                  <td><%= base.base_name %></td>
                  <td><%= base.attendance_type %></td>
              </tr>
              <% end %>
          </tbody>
      </table>
      <%= "拠点情報の追加（ボタン）" %>
    </div>
  </div>

  <!-- 2.モーダルの配置 -->
  <div class="modal" id="modal-sample" tabindex="-1">
      <div class="modal-dialog">
  
          <!-- 3.モーダルのコンテンツ -->
          <div class="modal-content">
              <!-- 4.モーダルのヘッダ -->
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">
                      <span aria-hidden="true">&times;</span>
                  </button>
                  <h4 class="modal-title" id="modal-label">拠点情報　【編集】</h4>
              </div>
              <!-- 5.モーダルのボディ -->
              <div class="modal-body">
                <%= render 'test00' %> <!-- ひとまず拠点編集テストページ作成 -->
                <!-- %= render 'base_edit_modal' % -->
              </div>
              <!-- 6.モーダルのフッタ -->
              <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
                  <button type="button" class="btn btn-primary">保存</button>
              </div>
          </div>
      </div>
  </div>

</html>

app/views/users/edit.html.erb
<% provide(:title, 'アカウント編集') %>
<% provide(:button_text, '更新する') %>
<h1>アカウント情報の更新</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "基本情報の修正") %>

<h1>基本情報の修正</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <!--<%= form_for(@user, url: update_basic_info_path(params: {id: @user.id})) do |f| %>-->
    <!--  <%= render 'shared/error_messages', object: @user %>-->

    <!--  <%= f.label :基本勤務時間 %>-->
    <!--  <%= f.time_field :basic_time, class: 'form-control' %>-->

    <!--  <%= f.label :指定勤務時間 %>-->
    <!--  <%= f.time_field :work_time, class: 'form-control' %>-->

    <!--  <%= f.submit "更新する", class: "btn btn-primary" %>-->
    <!--<% end %>-->
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, '一覧') %>

<h1>ユーザ一覧</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, '新規作成') %>
<% provide(:button_text, '作成する') %>
<h1>ユーザー作成</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, '勤怠表示') %>
<div>
  <table class = "table-bordered table-condensed">
    <tr>
      <td>
        <%= link_to "←", user_path(params: {id: @user.id, first_day: @first_day.prev_month }),
                         class: "btn btn-xs btn-primary" %>
        &emsp;<%= @first_day.to_s(:year_month) %>　時間管理表&emsp;
        <%= link_to "→", user_path(params: {id: @user.id, first_day: @first_day.next_month }),
                         class: "btn btn-xs btn-primary" %>
      </td>
      <td>指定勤務開始時間　<%= format_basic_time(@user.work_start) %><br>
          指定勤務終了時間　<%= format_basic_time(@user.work_end) %>
      </td>
      <td colspan = "3">基本時間　<%= format_basic_time(@user.basic_time) %></td>
      <td>初日　<%= @first_day.to_s(:date) %></td>
    </tr>
    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未設定" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>コード</td>
      <td>  </td>
      <td>出勤日数：<%= @worked_sum %>日</td>
      <td>締日　<%= @last_day.to_s(:date) %></td>
    </tr>
  </table>

  <%= link_to "勤怠を編集", edit_attendances_path(@user, @first_day), class: "btn btn-primary" %>
  <%= link_to "csvを出力", "#", class: "btn btn-primary" %>
  <%= link_to "勤怠修正ログ (承認済)", attendance_log_path, class: "btn btn-primary" %>

  <table class = "table-bordered table-striped table-condensed">
    <thead>
      <tr> <!--rowspan:縦結合、colspan：横結合-->
        <th rowspan = "3">残業申請</th>
        <th rowspan = "3">日付</th>
        <th rowspan = "3">曜日</th>
        <th colspan = "8">【実績】</th>
        <th colspan = "5">所定外勤務</th>
      </tr>
      <tr>
        <th colspan = "3">出社</th>
        <th colspan = "3">退社</th>
        <th rowspan = "2">在社時間</th>
        <th rowspan = "2">備考</th>
        <th colspan = "2">終了予定時刻</th>
        <th rowspan = "2">時間外時間</th>
        <th rowspan = "2">業務処理内容</th>
        <th rowspan = "2">指示者確認㊞</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>
    <tbody>
      <% @dates.each do |day| %>
        <tr>
          <td><%= "残業申請" %></td>
          <td><%= day.worked_on.to_s(:date) %></td>
          <td><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
          <td><%= day.started_at.to_s(:hour) if day.started_at.present? %></td>
          <td><%= day.started_at.to_s(:min) if day.started_at.present? %></td>
          <td>
            <% #9時間ずれをDate.currentで回避、Date.todayではだめ %>
            <% if day.worked_on == Date.current && day.started_at.nil? %>
              <%= button_to "出社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
            <% end %>
          </td>
          <td><%= day.finished_at.to_s(:hour) if day.finished_at.present? %></td>
          <td><%= day.finished_at.to_s(:min) if day.finished_at.present? %></td>
          <td>
            <% #9時間ずれをDate.currentで回避、Date.todayではだめ %>
            <% if day.worked_on == Date.current && day.started_at.present? && day.finished_at.nil? %>
              <%= button_to "退社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
            <% end %>
          </td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= working_times(day.started_at, day.finished_at) %>
              <% seconds = (day.finished_at - day.started_at).to_i %>
              <% @total_seconds = @total_seconds.to_i + seconds %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td><%= day.note %></td>
          <td><%= day.note %></td>
          <td><%= day.note %></td>
          <td><%= day.note %></td>
          <td><%= day.note %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td></td>
        <td colspan = "2"><%= format_basic_time(@user.basic_time).to_f * @worked_sum %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><%= working_times_sum(@total_seconds) unless @total_seconds.nil? %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>
          所属長承認<br>
          所属長承認
        </td>
        
      </tr>
    </tfoot>
  </table>
</div>

app/views/users/test01.html.erb
<% provide(:title, "拠点情報編集てすと") %>

<h1>拠点情報の編集てすと</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@base, url: update_test01_path(params: {id: @base.id})) do |f| %>
      <!-- %= render 'shared/error_messages', object: @base %>-->

      <%= f.label :base_number %>
      <%= f.text_field :base_number, class: 'form-control' %>

      <%= f.label :base_name %>
      <%= f.text_field :base_name, class: 'form-control' %>

      <%= f.submit "更新する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/working_users.html.erb
<% provide(:title, '出勤中社員一覧') %>
<% #provide(:path, users_working_users_path) %>
<h1>出勤中社員一覧</h1>

<%= will_paginate %>

<ul class="users">
  <%= render partial:'users/working_index', locals: { users: @users } %>
</ul>

<%= will_paginate %>