config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  # usersコントローラー
  get  '/signup', to: 'users#new'
  get '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update-basic-info', to: 'users#update_basic_info'
  get  '/attendance_log', to: 'users#attendance_log'
  get  '/working_users', to: 'users#working_users'
  get  '/base_edit', to: 'users#base_edit'
  
  #拠点テスト
  get  '/test00', to: 'users#test00'
  #get  '/test00/:id', to: 'users#test00', as: :test
  #patch 'update-test00', to: 'users#update_test00'
  
  #テスト発展
  get  '/test01/:id', to: 'users#test01', as: :test01
  patch 'update-test01', to: 'users#update_test01'
  
  #get  '/test00/:id', to: 'users#base_edit', as: :test00
  #patch 'update-test00', to: 'users#update_test01'
  
  
  # sessionsコントローラー
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # users>attendancesコントローラー
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances
  
  resources :users do
    resources :attendances, only: :create
    
    #拠点編集ページルーティング
    collection do
      #get  'base_edit'
      #post 'base_add'
      
      #get 'base_update'
      
      delete 'base_delete'
      #get 'base_edit_modal'
    end
    
    member do
      #ユーザー覧編集機能のため追加 membr do でルーティングする方法が不明（ない場合noMETHODエラー）
      patch  'update_by_admin'  #, as: :update_by_admin　ルートに名前をつける必要なし
    end
    
  end
  
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "勤怠システム", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "トップへ", root_path %></li>
        <% if logged_in? %>
          <!--管理者のみ[ユーザー覧],[基本情報修正]タグ表示-->
          <% if current_user.admin? %>
            <li><%= link_to "テスト00", test00_path %></li>
            <li><%= link_to "ユーザ一覧", users_path %></li>
            <li><%= link_to "出社社員一覧", working_users_path %></li>
            <li><%= link_to "拠点情報の修正", base_edit_path %></li>
            <% if params[:id].nil? %>
              <li><%= link_to "基本情報の修正", basic_info_path(current_user) %></li>
            <% else %>
              <li><%= link_to "基本情報の修正", basic_info_path(params[:id]) %></li>
            <% end %>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "ユーザー勤怠情報表示", current_user %></li>
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %> <!-- HTML shimがこの1行で済む -->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>